# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: "Checkout"
    - uses: actions/checkout@master

    - name: "Setup Node.js"
    - uses: actions/setup-node@v1
      with:
         node-version: 12.x

    - name: Cache node modules
    - uses: actions/cache@v1
      with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

    - name: npm install, npm run build:ci and setup angular
    - run: |  
          npm i  
          npm run build:ci
          npm install -g @angular/cli > /dev/null

    - name: Run Test
      run: ng t trato-ui
    
    - name: Run Lint
      run: ng lint
      
    - name: Run Build
      run: ng b trato ui --prod
    
    - name: Run Pack NPM
      run: npm pack
      
    
